packages:
  - 'frontend'
  - 'main'
  - 'packages/runpane'
  - 'shared'
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - electron
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
