// Generated by scripts/generate-runpane-contract.js. Do not edit by hand.

export const RUNPANE_CONTRACT = {
  "$schema": "./schema.json",
  "schemaVersion": 1,
  "name": "runpane",
  "description": "Thin installer and local control CLI for Pane",
  "packageInstallPolicy": [
    "The packages must not download, install, or configure Pane during package installation.",
    "Work starts only when a user runs `runpane ...`."
  ],
  "compatibility": {
    "node": ">=18.17.0",
    "python": ">=3.8"
  },
  "terminology": {
    "repo": "Saved Pane repository/project record",
    "pane": "User-visible Pane session",
    "tool": "Terminal-backed tab",
    "agent": "Built-in agent command template"
  },
  "defaults": {
    "target": "client",
    "paneVersion": "latest",
    "channel": "stable",
    "format": "auto",
    "dryRun": false,
    "yes": false,
    "verbose": false
  },
  "enums": {
    "installTargets": [
      "client",
      "daemon"
    ],
    "artifactFormats": [
      "auto",
      "appimage",
      "deb",
      "dmg",
      "zip",
      "exe"
    ],
    "channels": [
      "stable",
      "nightly"
    ],
    "agents": [
      "codex",
      "claude"
    ]
  },
  "agentTemplates": {
    "codex": {
      "title": "Codex",
      "command": "codex --yolo",
      "description": "Open a Codex terminal tab and allow the initial input to drive the agent."
    },
    "claude": {
      "title": "Claude Code",
      "command": "claude --dangerously-skip-permissions",
      "description": "Open a Claude Code terminal tab and allow the initial input to drive the agent."
    }
  },
  "commands": [
    {
      "name": "help",
      "summary": "Show help for runpane or a specific command.",
      "usage": [
        "runpane help [command]"
      ]
    },
    {
      "name": "setup",
      "summary": "Open the guided setup wizard for install, remote host setup, update, and diagnostics.",
      "usage": [
        "runpane setup"
      ],
      "interactiveEntrypoint": true
    },
    {
      "name": "install",
      "summary": "Install Pane on this machine or configure this machine as a remote daemon host.",
      "usage": [
        "runpane install [client|daemon] [options]"
      ],
      "defaultTarget": "client",
      "targets": [
        "client",
        "daemon"
      ],
      "unknownDaemonFlagsForwarded": true
    },
    {
      "name": "update",
      "summary": "Update the Pane desktop app using the same artifact path as install client.",
      "usage": [
        "runpane update [options]"
      ],
      "target": "client"
    },
    {
      "name": "version",
      "summary": "Print the runpane wrapper version and installed Pane version when detectable.",
      "usage": [
        "runpane version",
        "runpane --version"
      ]
    },
    {
      "name": "doctor",
      "summary": "Run platform, release, installed Pane, and remote setup diagnostics.",
      "usage": [
        "runpane doctor"
      ]
    },
    {
      "name": "repos list",
      "summary": "List repositories saved in the running Pane app.",
      "usage": [
        "runpane repos list [--json] [--pane-dir <path>]"
      ],
      "jsonSchemas": [
        "repoListResult"
      ]
    },
    {
      "name": "panes create",
      "summary": "Create one or more Pane sessions in a saved repository and open a terminal-backed tool tab.",
      "usage": [
        "runpane panes create --repo <selector> --name <name> --agent <codex|claude> [options]",
        "runpane panes create --from-json <path|-> [--yes] [--json]"
      ],
      "mutates": true,
      "jsonSchemas": [
        "paneCreateRequest",
        "paneCreateResult"
      ]
    }
  ],
  "flags": {
    "wrapper": [
      {
        "name": "--version",
        "value": "<latest|vX.Y.Z>",
        "description": "Pane release to install or inspect."
      },
      {
        "name": "--download-dir",
        "value": "<path>",
        "description": "Directory for downloaded Pane release artifacts."
      },
      {
        "name": "--pane-path",
        "value": "<path>",
        "description": "Use or inspect an existing Pane executable."
      },
      {
        "name": "--format",
        "value": "<auto|appimage|deb|dmg|zip|exe>",
        "description": "Pane release artifact format."
      },
      {
        "name": "--dry-run",
        "description": "Print the plan without downloading or installing."
      },
      {
        "name": "--yes",
        "aliases": [
          "-y"
        ],
        "description": "Skip interactive prompts where possible."
      },
      {
        "name": "--verbose",
        "description": "Print extra diagnostics."
      }
    ],
    "remoteValue": [
      {
        "name": "--label",
        "value": "<name>"
      },
      {
        "name": "--prefer-tunnel",
        "value": "<tailscale|ssh|manual|auto>"
      },
      {
        "name": "--channel",
        "value": "<stable|nightly>"
      },
      {
        "name": "--base-url",
        "value": "<url>"
      },
      {
        "name": "--pane-dir",
        "value": "<path>"
      },
      {
        "name": "--listen-port",
        "value": "<port>"
      },
      {
        "name": "--port",
        "value": "<port>"
      },
      {
        "name": "--repo-ref",
        "value": "<ref>"
      }
    ],
    "remoteBoolean": [
      {
        "name": "--auto-listen-port"
      },
      {
        "name": "--interactive-tailscale-setup"
      },
      {
        "name": "--no-install-service"
      },
      {
        "name": "--no-tailscale-serve"
      },
      {
        "name": "--print-only"
      }
    ],
    "localValue": [
      {
        "name": "--pane-dir",
        "value": "<path>",
        "description": "Connect to a Pane daemon using this Pane data directory."
      },
      {
        "name": "--repo",
        "value": "<selector>",
        "description": "Repository selector: active, id, exact path, or saved repository name."
      },
      {
        "name": "--name",
        "value": "<name>",
        "description": "Name for the created pane/session."
      },
      {
        "name": "--worktree-name",
        "value": "<name>",
        "description": "Worktree name to request. Defaults to --name."
      },
      {
        "name": "--base-branch",
        "value": "<branch>",
        "description": "Base branch for the created worktree."
      },
      {
        "name": "--agent",
        "value": "<codex|claude>",
        "description": "Built-in agent terminal template to open."
      },
      {
        "name": "--tool-command",
        "value": "<command>",
        "description": "Custom terminal command to run instead of a built-in agent."
      },
      {
        "name": "--title",
        "value": "<title>",
        "description": "Terminal tab title. Defaults to the selected agent title or Terminal."
      },
      {
        "name": "--initial-input",
        "value": "<text>",
        "aliases": [
          "--prompt"
        ],
        "description": "Text to send to the terminal after the command is ready. --prompt is an alias."
      },
      {
        "name": "--initial-input-file",
        "value": "<path|->",
        "description": "Read initial input from a file or stdin."
      },
      {
        "name": "--from-json",
        "value": "<path|->",
        "description": "Read a full panes.create request JSON payload from a file or stdin."
      },
      {
        "name": "--timeout-ms",
        "value": "<milliseconds>",
        "description": "Maximum time to wait for each pane creation job."
      }
    ],
    "localBoolean": [
      {
        "name": "--json",
        "description": "Print machine-readable JSON output."
      }
    ]
  },
  "help": {
    "npm": {
      "default": [
        "Usage:",
        "  runpane",
        "  runpane setup",
        "  runpane install [client|daemon] [options]",
        "  runpane update [options]",
        "  runpane version",
        "  runpane doctor",
        "  runpane repos list [--json]",
        "  runpane panes create --repo <selector> --name <name> --agent <codex|claude>",
        "  runpane help [command]",
        "",
        "Quick start:",
        "  npx --yes runpane@latest",
        "  npm i -g runpane && runpane setup",
        "",
        "Advanced examples:",
        "  npx --yes runpane@latest install client",
        "  npx --yes runpane@latest install daemon --label \"My Server\"",
        "  pnpm dlx runpane@latest",
        "  pipx run runpane",
        "",
        "Run \"runpane help panes create\" for pane orchestration options."
      ],
      "install": [
        "Usage:",
        "  runpane install [client|daemon] [options]",
        "",
        "Examples:",
        "  npx --yes runpane@latest install client",
        "  npx --yes runpane@latest install daemon --label \"My Server\"",
        "  pnpm dlx runpane@latest install daemon --prefer-tunnel ssh --label \"VM\"",
        "",
        "Wrapper options:",
        "  --version <latest|vX.Y.Z>        Pane release to install",
        "  --format <auto|appimage|deb|dmg|zip|exe>",
        "  --download-dir <path>",
        "  --pane-path <path>               Use an existing Pane executable",
        "  --dry-run                       Print the plan without downloading",
        "  --yes                           Skip interactive prompts where possible",
        "  --verbose",
        "",
        "Daemon passthrough options:",
        "  --label <name>",
        "  --prefer-tunnel <tailscale|ssh|manual|auto>",
        "  --channel <stable|nightly>",
        "  --base-url <url>",
        "  --pane-dir <path>",
        "  --listen-port <port> / --port <port>",
        "  --auto-listen-port",
        "  --interactive-tailscale-setup",
        "  --no-install-service",
        "  --no-tailscale-serve",
        "  --print-only",
        "  --repo-ref <ref>"
      ],
      "setup": [
        "Usage:",
        "  runpane setup",
        "",
        "Opens the guided setup for desktop install, remote host setup, update, and diagnostics.",
        "",
        "Quick start:",
        "  npx --yes runpane@latest",
        "  npm i -g runpane && runpane setup"
      ],
      "update": [
        "Usage:",
        "  runpane update [options]",
        "",
        "Updates Pane using the same artifact selection as \"runpane install client\".",
        "",
        "Options:",
        "  --version <latest|vX.Y.Z>",
        "  --format <auto|appimage|deb|dmg|zip|exe>",
        "  --download-dir <path>",
        "  --pane-path <path>",
        "  --dry-run",
        "  --yes",
        "  --verbose"
      ],
      "version": [
        "Usage:",
        "  runpane version",
        "  runpane --version"
      ],
      "doctor": [
        "Usage:",
        "  runpane doctor [--pane-path <path>] [--format <format>] [--verbose]"
      ],
      "repos list": [
        "Usage:",
        "  runpane repos list [--json] [--pane-dir <path>]",
        "",
        "Lists repositories saved in the running Pane app.",
        "",
        "Options:",
        "  --json                         Print machine-readable output",
        "  --pane-dir <path>              Connect to a specific Pane data directory"
      ],
      "panes create": [
        "Usage:",
        "  runpane panes create --repo <selector> --name <name> --agent <codex|claude> [options]",
        "  runpane panes create --from-json <path|-> [--yes] [--json]",
        "",
        "Creates Pane sessions in a saved repository and opens a terminal-backed tool tab.",
        "",
        "Options:",
        "  --repo <selector>              active, id, exact path, or saved repository name",
        "  --name <name>                  Pane/session name",
        "  --worktree-name <name>         Worktree name; defaults to --name",
        "  --base-branch <branch>         Base branch for the worktree",
        "  --agent <codex|claude>         Built-in terminal template",
        "  --tool-command <command>       Custom terminal command",
        "  --title <title>                Terminal tab title",
        "  --initial-input <text>         Text sent after the command is ready",
        "  --prompt <text>                Alias for --initial-input",
        "  --initial-input-file <path|->  Read initial input from a file or stdin",
        "  --from-json <path|->           Read a full request payload",
        "  --timeout-ms <milliseconds>    Pane creation timeout",
        "  --pane-dir <path>              Connect to a specific Pane data directory",
        "  --json                         Print machine-readable output",
        "  --dry-run                      Validate and preview without creating panes",
        "  --yes                          Skip confirmation for mutating commands"
      ]
    },
    "pip": {
      "default": [
        "Usage:",
        "  runpane",
        "  runpane setup",
        "  runpane install [client|daemon] [options]",
        "  runpane update [options]",
        "  runpane version",
        "  runpane doctor",
        "  runpane repos list [--json]",
        "  runpane panes create --repo <selector> --name <name> --agent <codex|claude>",
        "  runpane help [command]",
        "",
        "Quick start:",
        "  pipx run runpane",
        "  python -m pip install runpane && python -m runpane setup",
        "",
        "Advanced examples:",
        "  pipx run runpane install client",
        "  pipx run runpane install daemon --label \"My Server\"",
        "  uvx runpane@latest",
        "",
        "Run \"runpane help panes create\" for pane orchestration options."
      ],
      "install": [
        "Usage:",
        "  runpane install [client|daemon] [options]",
        "",
        "Examples:",
        "  npx --yes runpane@latest install daemon --label \"My Server\"",
        "  pnpm dlx runpane@latest install daemon --prefer-tunnel ssh --label \"VM\"",
        "  pipx run runpane install daemon --label \"My Server\"",
        "",
        "Wrapper options:",
        "  --version <latest|vX.Y.Z>",
        "  --format <auto|appimage|deb|dmg|zip|exe>",
        "  --download-dir <path>",
        "  --pane-path <path>",
        "  --dry-run",
        "  --yes",
        "  --verbose",
        "",
        "Daemon passthrough options:",
        "  --label <name>",
        "  --prefer-tunnel <tailscale|ssh|manual|auto>",
        "  --channel <stable|nightly>",
        "  --base-url <url>",
        "  --pane-dir <path>",
        "  --listen-port <port> / --port <port>",
        "  --auto-listen-port",
        "  --interactive-tailscale-setup",
        "  --no-install-service",
        "  --no-tailscale-serve",
        "  --print-only",
        "  --repo-ref <ref>"
      ],
      "setup": [
        "Usage:",
        "  runpane setup",
        "",
        "Opens the guided setup for desktop install, remote host setup, update, and diagnostics.",
        "",
        "Quick start:",
        "  pipx run runpane",
        "  python -m pip install runpane && python -m runpane setup"
      ],
      "update": [
        "Usage:",
        "  runpane update [--version <latest|vX.Y.Z>] [--dry-run] [--yes]"
      ],
      "version": [
        "Usage:",
        "  runpane version",
        "  runpane --version"
      ],
      "doctor": [
        "Usage:",
        "  runpane doctor [--pane-path <path>] [--format <format>] [--verbose]"
      ],
      "repos list": [
        "Usage:",
        "  runpane repos list [--json] [--pane-dir <path>]",
        "",
        "Lists repositories saved in the running Pane app.",
        "",
        "Options:",
        "  --json",
        "  --pane-dir <path>"
      ],
      "panes create": [
        "Usage:",
        "  runpane panes create --repo <selector> --name <name> --agent <codex|claude> [options]",
        "  runpane panes create --from-json <path|-> [--yes] [--json]",
        "",
        "Creates Pane sessions in a saved repository and opens a terminal-backed tool tab.",
        "",
        "Options:",
        "  --repo <selector>",
        "  --name <name>",
        "  --worktree-name <name>",
        "  --base-branch <branch>",
        "  --agent <codex|claude>",
        "  --tool-command <command>",
        "  --title <title>",
        "  --initial-input <text>",
        "  --prompt <text>",
        "  --initial-input-file <path|->",
        "  --from-json <path|->",
        "  --timeout-ms <milliseconds>",
        "  --pane-dir <path>",
        "  --json",
        "  --dry-run",
        "  --yes"
      ]
    }
  },
  "docs": {
    "maintainerRules": [
      "Treat `contracts/runpane/contract.json` as the source of truth for both wrapper packages and generated docs.",
      "Every command, flag, platform default, artifact-selection rule, and attribution rule change must be reflected in the contract.",
      "The npm and PyPI wrappers must expose the same command behavior unless the contract explicitly documents a package-manager-specific difference.",
      "Root `README.md` and package READMEs should lead with one guided quick-start command. Explicit commands, package-manager variants, and flags belong in an Advanced section.",
      "Release version bumps must keep root `package.json`, `packages/runpane`, and `packages/runpane-py` versions in sync. Run `pnpm run check:runpane-package-versions` before release.",
      "`pnpm run test:runpane-contract` must pass before changing wrapper command parsing, help output, platform defaults, release asset selection, or generated contract artifacts.",
      "Token-based npm or PyPI publishing is a temporary fallback. Prefer trusted publishing once the package names are reserved and trusted publishers are configured."
    ],
    "recommendedQuickStarts": [
      "npx --yes runpane@latest",
      "npm i -g runpane && runpane setup",
      "pipx run runpane",
      "python -m pip install runpane && python -m runpane setup"
    ],
    "npmCommands": [
      "npx --yes runpane@latest",
      "npx --yes runpane@latest setup",
      "npx --yes runpane@latest install client",
      "npx --yes runpane@latest install daemon --label \"My Server\"",
      "pnpm dlx runpane@latest",
      "pnpm dlx runpane@latest install daemon --label \"My Server\"",
      "npm i -g runpane && runpane",
      "npm i -g runpane && runpane setup",
      "npm i -g runpane && runpane install daemon --label \"My Server\"",
      "pnpm add -g runpane && runpane",
      "pnpm add -g runpane && runpane setup",
      "pnpm add -g runpane && runpane install daemon --label \"My Server\"",
      "yarn dlx runpane@latest install daemon --label \"My Server\"",
      "bunx runpane@latest install daemon --label \"My Server\""
    ],
    "pythonCommands": [
      "pipx run runpane",
      "pipx run runpane setup",
      "python -m pip install runpane",
      "runpane",
      "runpane setup",
      "python -m runpane setup",
      "runpane install daemon --label \"My Server\"",
      "pipx install runpane",
      "runpane",
      "runpane setup",
      "pipx run runpane install daemon --label \"My Server\"",
      "uvx runpane@latest",
      "uvx runpane@latest setup",
      "uvx runpane@latest install daemon --label \"My Server\"",
      "python -m runpane install daemon --label \"My Server\""
    ],
    "packageManagerNotes": [
      "Use `pnpm dlx` for one-shot pnpm execution and `pnpm add -g` for persistent CLI installation.",
      "Do not document `pnpm install runpane` as the public CLI install path."
    ],
    "commandUsages": [
      "runpane",
      "runpane setup",
      "runpane install",
      "runpane install client",
      "runpane install daemon",
      "runpane update",
      "runpane version",
      "runpane doctor",
      "runpane repos list --json",
      "runpane panes create --repo active --name issue-252 --agent codex --prompt \"Kick off the discussion skill for issue 252\" --yes",
      "runpane panes create --from-json panes.json --yes --json",
      "runpane help",
      "runpane <command> --help"
    ],
    "commandDescriptions": [
      "`runpane` with no arguments and `runpane setup` open an interactive wizard when stdin and stdout are TTYs. In non-interactive shells or CI, both forms must print help and exit successfully instead of waiting for input.",
      "`runpane install` is an alias for `runpane install client`.",
      "`runpane install client` downloads the selected Pane desktop artifact and installs, opens, or launches it for the current platform.",
      "`runpane install daemon` downloads or installs Pane, resolves a stable Pane executable path, and spawns `<pane executable> --remote-setup <forwarded remote setup args>`.",
      "The wrapper must stream Pane stdout/stderr without reformatting because `pane --remote-setup` prints the one-time `pane-remote://...` connection code.",
      "`runpane update` uses the same release resolution and installer path as `install client`.",
      "`runpane version` prints the wrapper package version, the installed Pane version when detectable, and the latest GitHub release version when reachable.",
      "`runpane doctor` checks platform support, release metadata reachability, download URL selection, installed Pane detection, and remote-daemon hints.",
      "`runpane repos list` connects to the running local Pane daemon and prints saved repository records.",
      "`runpane panes create` connects to the running local Pane daemon, resolves the requested repository, creates Pane sessions, opens terminal-backed tool tabs, and optionally sends initial input to the started tool.",
      "`runpane panes create --prompt` is an alias for `--initial-input`; request JSON and daemon payloads should use the canonical `initialInput` field."
    ],
    "wrapperFlagNote": "The top-level `runpane --version` form prints the wrapper version. The install subcommand form `runpane install --version vX.Y.Z` selects a Pane release.",
    "localControlFlagNote": "`runpane repos list` and `runpane panes create` use the local framed daemon socket/pipe for a running Pane app. `--pane-dir` points the wrapper at a non-default Pane data directory, such as `PANE_DIR=~/.pane_test` in development.",
    "daemonFlagNote": "Unknown daemon flags should be forwarded rather than dropped so newer Pane versions can extend `--remote-setup` without requiring an immediate wrapper release. Unknown flags for non-daemon commands should fail clearly.",
    "downloadAttribution": [
      "The npm package uses `source=npm` for all npm-registry consumers, including `npx`, `pnpm dlx`, `yarn dlx`, `bunx`, and global npm/pnpm installs.",
      "The PyPI package uses `source=pip` for all Python consumers, including pip, pipx, uvx, and `python -m runpane`.",
      "Wrappers should prefer `https://runpane.com/api/download?platform=<platform>&arch=<arch>&format=<format>&version=<version>&channel=<channel>&source=<npm|pip>`.",
      "If the website route cannot satisfy the download, wrappers may fall back to the matching GitHub release asset and print a warning that website attribution may be incomplete for that run."
    ],
    "publishingCredentials": [
      "Local implementation, build, and dry-run validation do not need npm or PyPI API tokens.",
      "Release publishing should prefer npm Trusted Publishing and PyPI Trusted Publishing from GitHub Actions.",
      "Fallback `NPM_TOKEN` or `PYPI_API_TOKEN` credentials may be used for first package reservation or manual publication only. They must be supplied through local environment variables or GitHub Actions secrets, never committed, and revoked or rotated after use."
    ]
  },
  "testFixtures": {
    "parserSamples": [
      [
        "setup"
      ],
      [
        "install"
      ],
      [
        "install",
        "client",
        "--version",
        "v2.2.8",
        "--format",
        "dmg",
        "--download-dir",
        "/tmp/pane-downloads",
        "--dry-run",
        "--yes"
      ],
      [
        "install",
        "daemon",
        "--label",
        "VM",
        "--prefer-tunnel",
        "ssh",
        "--channel",
        "nightly",
        "--base-url",
        "https://example.test",
        "--pane-dir",
        "/tmp/pane",
        "--listen-port",
        "4555",
        "--auto-listen-port",
        "--print-only",
        "--repo-ref",
        "main",
        "--unknown-future-flag",
        "future-value",
        "--dry-run",
        "--verbose"
      ],
      [
        "update",
        "--version",
        "latest",
        "--format",
        "appimage",
        "--pane-path",
        "/usr/bin/pane",
        "--dry-run"
      ],
      [
        "doctor",
        "--pane-path",
        "/usr/bin/pane",
        "--format",
        "zip",
        "--verbose"
      ],
      [
        "repos",
        "list",
        "--json",
        "--pane-dir",
        "/tmp/pane"
      ],
      [
        "panes",
        "create",
        "--repo",
        "active",
        "--name",
        "issue-252",
        "--agent",
        "codex",
        "--prompt",
        "Kick off discussion",
        "--dry-run",
        "--yes",
        "--json"
      ],
      [
        "panes",
        "create",
        "--from-json",
        "-",
        "--yes",
        "--json"
      ],
      [
        "--version"
      ]
    ],
    "topLevelHelpIncludes": [
      "runpane setup",
      "runpane install",
      "runpane update",
      "runpane version",
      "runpane doctor",
      "runpane repos list",
      "runpane panes create"
    ],
    "npmHelpIncludes": [
      "pnpm dlx runpane@latest",
      "npx --yes runpane@latest"
    ],
    "pipHelpIncludes": [
      "pipx run runpane",
      "python -m pip install runpane && python -m runpane setup"
    ],
    "installHelpIncludes": [
      "--version <latest|vX.Y.Z>",
      "--format <auto|appimage|deb|dmg|zip|exe>",
      "--download-dir <path>",
      "--pane-path <path>",
      "--label <name>",
      "--prefer-tunnel <tailscale|ssh|manual|auto>",
      "--repo-ref <ref>"
    ]
  },
  "jsonSchemas": {
    "error": {
      "type": "object",
      "required": [
        "ok",
        "error"
      ],
      "properties": {
        "ok": {
          "const": false
        },
        "error": {
          "type": "object",
          "required": [
            "message"
          ],
          "properties": {
            "message": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "repoListResult": {
      "type": "object",
      "required": [
        "ok",
        "repos"
      ],
      "properties": {
        "ok": {
          "const": true
        },
        "repos": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "id",
              "name",
              "path",
              "active",
              "sessionCount"
            ],
            "properties": {
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "path": {
                "type": "string"
              },
              "active": {
                "type": "boolean"
              },
              "environment": {
                "type": "string"
              },
              "sessionCount": {
                "type": "number"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "paneCreateRequest": {
      "type": "object",
      "required": [
        "repo",
        "panes"
      ],
      "properties": {
        "repo": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number"
                },
                "path": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "active": {
                  "const": true
                }
              },
              "additionalProperties": false
            }
          ]
        },
        "panes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "name",
              "tool"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "worktreeName": {
                "type": "string"
              },
              "baseBranch": {
                "type": "string"
              },
              "sessionPrompt": {
                "type": "string"
              },
              "tool": {
                "oneOf": [
                  {
                    "type": "object",
                    "required": [
                      "agent"
                    ],
                    "properties": {
                      "agent": {
                        "enum": [
                          "codex",
                          "claude"
                        ]
                      },
                      "title": {
                        "type": "string"
                      },
                      "initialInput": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "required": [
                      "command"
                    ],
                    "properties": {
                      "command": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "initialInput": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "dryRun": {
          "type": "boolean"
        },
        "timeoutMs": {
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "paneCreateResult": {
      "type": "object",
      "required": [
        "ok",
        "repo",
        "items"
      ],
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "repo": {
          "$ref": "#/jsonSchemas/repoListResult/properties/repos/items"
        },
        "items": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "required": [
                  "ok",
                  "index",
                  "name"
                ],
                "properties": {
                  "ok": {
                    "const": true
                  },
                  "index": {
                    "type": "number"
                  },
                  "name": {
                    "type": "string"
                  },
                  "sessionId": {
                    "type": "string"
                  },
                  "paneId": {
                    "type": "string"
                  },
                  "panelId": {
                    "type": "string"
                  },
                  "worktreePath": {
                    "type": "string"
                  },
                  "tool": {
                    "type": "object",
                    "required": [
                      "title",
                      "command"
                    ],
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "command": {
                        "type": "string"
                      },
                      "agent": {
                        "enum": [
                          "codex",
                          "claude"
                        ]
                      }
                    },
                    "additionalProperties": false
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "object",
                "required": [
                  "ok",
                  "index",
                  "error"
                ],
                "properties": {
                  "ok": {
                    "const": false
                  },
                  "index": {
                    "type": "number"
                  },
                  "name": {
                    "type": "string"
                  },
                  "error": {
                    "type": "object",
                    "required": [
                      "message"
                    ],
                    "properties": {
                      "message": {
                        "type": "string"
                      },
                      "code": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        }
      },
      "additionalProperties": false
    }
  }
} as const;

export type RunpaneCommand = typeof RUNPANE_CONTRACT.commands[number]['name'];
export type InstallTarget = typeof RUNPANE_CONTRACT.enums.installTargets[number];
export type ArtifactFormat = typeof RUNPANE_CONTRACT.enums.artifactFormats[number];
export type RunpaneChannel = typeof RUNPANE_CONTRACT.enums.channels[number];
export type RunpaneAgent = typeof RUNPANE_CONTRACT.enums.agents[number];
